theme: jekyll-theme-slate
title: Tubefeeder
description: "A Youtube, Lbry and Peertube client made for the Pinephone"

github:
  is_project_page: true
  repository_url: "https://github.com/Tubefeeder/Tubefeeder"

